[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
PythonCall = "=0.9.26"
OpenSSL_jll = "3.0.0 - 3.6"
SymbolicRegression = "~1.11"
Serialization = "^1"
