name: neural-graph
channels:
  - conda-forge
dependencies:
  - python=3.10.0
  - umap-learn
  - numpy
  - scipy
  - ipython
  - pandas
  - matplotlib
  - networkx
  - prettytable
  - tqdm
  - PyYAML
  - tifffile
  - pydantic
  - gputil
  - pip
  - imageio
  - astropy
  - scikit-image
  - pysr
  - shapely
  - seaborn
  - dask
  - pyvista
  - tensorstore
  - napari
  - pip:
    # Install PyTorch with CUDA support via pip
    - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
    - geomloss
    - torch_geometric
    - PyQt5
    - tables
    - vedo
    - joblib
    - flyvis
    - opencv-python
    
