description: 'n_frames: 1500  hidden 512 learning_rate_NNR_f 1.0E-5 taxis only'
dataset: 'zebra_N10_33_4'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/Zapbench/zapbench_numpy'

simulation:
    connectivity_file: 'to be specified'
    adjacency_matrix: ''

    params: [[1.0,1.0,1.0,1.0]]

    n_neurons: 71721
    n_input_neurons: 1736
    n_neuron_types: 65
    n_frames: 7879
    delta_t: 1
    baseline_value: 0

    visual_input_type: "taxis"

graph_model:
    signal_model_name: 'PDE_N10'
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 32
    n_layers: 2

    input_size_update: 5
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2

    input_size_nnr_f: 4
    hidden_dim_nnr_f: 512
    n_layers_nnr_f: 3
    omega_f: 10
    outermost_linear_nnr_f: True
    output_size_nnr_f: 1
    nnr_f_xy_period: 0.406
    nnr_f_T_period: 1500

    aggr_type: 'add'
    embedding_dim: 2

    update_type: 'generic'
    lin_edge_positive: True


plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [ -2.5,2.5 ]
    ylim: [ -100,100 ]

training:
    n_epochs: 20
    n_runs: 1
    device: 'auto'

    batch_size: 1
    batch_ratio: 0.15

    sparsity: 'none'
    data_augmentation_loop: 25

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3
    learning_rate_NNR_f: 1.0E-5

    measurement_noise_level: 0
    noise_model_level: 0
    coeff_edge_diff: 500
    coeff_update_u_diff: 0
    coeff_update_msg_diff: 0
    coeff_edge_norm: 1000.0
