description: 'no extra null edges, noise_model_level: 0  coeff_edge_diff: 0 coeff_edge_norm: 0  training seed: 24   benchmark RNN  training on neuron 4193  Mi2 1000 frame'
dataset: 'fly_N9_18_4_0'

simulation:
    connectivity_file: 'to be specified'
    adjacency_matrix: ''

    params: [[1.0,1.0,1.0,1.0]]

    n_neurons: 1
    n_input_neurons: 1
    n_neuron_types: 65
    n_edges: 434112
    n_frames: 1000
    delta_t: 0.02
    baseline_value: 0

graph_model:
    signal_model_name: 'PDE_N9_RNN'
    prediction: 'first_derivative'

    input_size: 2
    output_size: 1
    hidden_dim: 256
    n_layers: 3
    MLP_activation: 'relu'


    aggr_type: 'add'
    embedding_dim: 2

    update_type: 'generic'
    lin_edge_positive: True


plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [ -2.5,5 ]
    ylim: [ -100,100 ]

training:
    n_epochs: 10
    n_runs: 1
    device: 'auto'
    seed: 241

    training_selected_neurons: True
    selected_neuron_ids: [4193]

    batch_size: 1
    batch_ratio: 1

    sparsity: 'none'
    rotation_augmentation: False
    data_augmentation_loop: 250

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3

    measurement_noise_level: 0
    noise_model_level: 0
    coeff_edge_diff: 0
    coeff_update_u_diff: 0
    coeff_update_msg_diff: 0
    coeff_edge_norm: 0
