description: designed by Claude (parallel)
dataset: signal_landscape_Claude_01
simulation:
  connectivity_type: chaotic
  connectivity_rank: 20
  Dale_law: false
  Dale_law_factor: 0.5
  connectivity_init:
  - 0
  - 0.1
  connectivity_filling_factor: 1
  params:
  - - 1.0
    - 0.0
    - 2.0
    - 0.0
    - 1.0
    - 0.0
  phi: tanh
  n_neurons: 200
  n_neuron_types: 1
  n_frames: 30000
  delta_t: 0.01
  dpos_init: 0
  boundary: 'no'
  start_frame: -100
  noise_model_level: 0
graph_model:
  signal_model_name: PDE_N4
  particle_model_name: ''
  mesh_model_name: ''
  prediction: first_derivative
  input_size: 3
  output_size: 1
  hidden_dim: 64
  n_layers: 3
  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64
  aggr_type: add
  embedding_dim: 2
  update_type: none
claude:
  n_epochs: 10
  data_augmentation_loop: 40
  n_iter_block: 12
  ucb_c: 1.414
  node_name: a100
plotting:
  colormap: tab10
  arrow_length: 1
  xlim:
  - -5
  - 5
  ylim:
  - -2
  - 2
training:
  n_epochs: 10
  n_runs: 1
  device: cuda:0
  batch_size: 8
  small_init_batch_size: false
  seed: 24
  data_augmentation_loop: 40
  sparsity: replace_embedding_function
  sparsity_freq: 4
  cluster_method: distance_plot
  cluster_distance_threshold: 0.1
  fix_cluster_embedding: true
  learning_rate_W_start: 0.0003
  learning_rate_start: 0.0001
  learning_rate_embedding_start: 0.001
  coeff_W_L1: 1.0e-05
  n_epochs_init: 0
  first_coeff_L1: 0
  coeff_lin_phi_zero: 0
  coeff_edge_diff: 100
  recurrent_training: false
  time_step: 1
  noise_recurrent_level: 0.0
  recurrent_training_start_epoch: 0
