description: designed by Claude
dataset: signal_landscape_Claude_repeat
simulation:
  connectivity_type: chaotic
  connectivity_rank: 20
  connectivity_init:
  - 0
  - 0.1
  connectivity_filling_factor: 0.5
  Dale_law: false
  Dale_law_factor: 0.5
  noise_model_level: 0
  params:
  - - 1.0
    - 0.0
    - 10.0
    - 0.0
    - 1.0
    - 0.0
  - - 1.0
    - 0.0
    - 10.0
    - 1.0
    - 1.0
    - 0.0
  - - 2.0
    - 0.0
    - 10.0
    - 1.0
    - 1.0
    - 0.0
  - - 2.0
    - 0.0
    - 10.0
    - 2.0
    - 1.0
    - 0.0
  phi: tanh
  n_neurons: 100
  n_neuron_types: 1
  n_frames: 10000
  delta_t: 0.01
  dpos_init: 0
  boundary: 'no'
  start_frame: -100
graph_model:
  signal_model_name: PDE_N4
  particle_model_name: ''
  mesh_model_name: ''
  prediction: first_derivative
  input_size: 3
  output_size: 1
  hidden_dim: 64
  n_layers: 3
  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64
  aggr_type: add
  update_type: none
claude:
  n_epochs: 2
  data_augmentation_loop: 500
  n_iter_block: 8
  ucb_c: 1.414
  node_name: a100
plotting:
  colormap: tab10
  arrow_length: 1
  xlim:
  - -5
  - 5
  ylim:
  - -2
  - 2
training:
  n_epochs: 2
  n_runs: 1
  device: cuda:0
  batch_size: 8
  small_init_batch_size: false
  seed: 24
  data_augmentation_loop: 500
  sparsity: replace_embedding_function
  sparsity_freq: 4
  cluster_method: distance_plot
  cluster_distance_threshold: 0.1
  fix_cluster_embedding: true
  learning_rate_W_start: 0.01
  learning_rate_start: 0.001
  learning_rate_embedding_start: 0.00025
  n_epochs_init: 1
  first_coeff_L1: 0
  coeff_W_L1: 0
  coeff_edge_diff: 100
  low_rank_factorization: false
  low_rank: 20
